# Generated by Django 3.2.6 on 2021-08-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210820_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='pending',
            field=models.CharField(choices=[('P', 'Pending...'), ('A', 'Approved'), ('D', 'Denied')], default='P', max_length=1),
        ),
    ]
