# Generated by Django 3.2.6 on 2021-08-24 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_cat_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='pending',
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.CharField(choices=[('P', 'Pending...'), ('A', 'Approved'), ('D', 'Denied')], default='P', max_length=1)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cat')),
            ],
        ),
    ]
