# Generated by Django 3.2.6 on 2021-08-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210824_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='pending',
            field=models.CharField(choices=[('P', 'Pending...'), ('A', 'Approved'), ('D', 'Denied')], default='P', max_length=1),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
