# Generated by Django 3.2.4 on 2021-08-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_cat_pending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='breed',
            new_name='species',
        ),
    ]
